<?xml version='1.0' encoding='utf-8'?>
<testsuites>
  <testsuite name="C:\Jenkins\jobs\my-project\workspace\MyProject\MyProject.Tests\bin\Release\MyProject.Tests.DLL" tests="3" failures="1" errors="0" time="0.288" skipped="1" timestamp="2014-12-18T14:34:32">
    <testsuite name="Test collection for MyProject.Tests.SampleFact" tests="3" failures="1" time="0.025" skipped="1">
      <testcase name="FailedTest" time="0.014" classname="MyProject.Tests.SampleFact">
        <failure type="Xunit.Sdk.TrueException" message="Assert.True() Failure">Assert.True() Failure   at MyProject.Tests.SampleFact.FailedTest() in c:\Jenkins\jobs\my-project\workspace\MyProject\MyProject.Tests\SampleFact.cs:line 16</failure>
      </testcase>
      <testcase name="SuccessfulTest" time="0.010" classname="MyProject.Tests.SampleFact"/>
      <testcase name="SkippedTest" time="0.000" classname="MyProject.Tests.SampleFact">
        <skipped message="On Purpose"/>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
